name: Refresh Database

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  RefreshData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - uses: BSFishy/pip-action@v1
        with:
          packages: pyodbc
      - run: |
          pwd
          cd RefreshDB
          python RefreshDatabase.py ${{ secrets.CONNECTION_STRING }} 

